### ISSUE TITLE
Get vehicles list

### ISSUE THREAD

**Issue by Poque13** [rklf/paybybot3#1]
Hi,

first of all thank you for your project!
i wanted to add a function in the bot to get all vehicles from an account but i have an error. For the link of the api, i used this repo "https://github.com/itsff/PayByPhone-api-docs/blob/master/Vehicles.apib",
so my function is like :
    def _get_vehicles(self):
        return self._get(
            "https://consumer.paybyphoneapis.com/parking/accounts/%s/vehicles" % self.parkingAccountId,
            params={
                "parkingAccountId": self.parkingAccountId,
            },
        ).json()

Do you know what is the problem, or will you add some features related to vehicles for the bot? For example adding new vehicles to an account? 

Thanks in advance for your answer

**Comment by rklf** [comment]
Hey,

I've just added that option in paybybot3. Use ``pip install paybybot3 --upgrade`` to update package then you should be able to use ``paybybot3 vehicles --config [CONFIG_FILE] [CONFIG_NAME]`` to show all vehicles added to the account

FYI you can check updated code in that PR #2
