### ISSUE TITLE
Where find doc of "paybyphoneapis.com"

### ISSUE THREAD

**Issue by dev590t** [rklf/paybybot3#10]
I would like contribute to the project. I'm trying to understand the code base. I see `paybybot3` use `paybyphoneapis.com`.

But I don't find any information about `paybyphoneapis.com` on Google . Is it a official REST API provided by PayByPhone? Where I can find a documentation about how using this API?

**Comment by rklf** [comment]
There is no documentation for this seen that this is not an official API. Code is from a reverse engineering process.

Closing.

**Comment by dev590t** [comment]
the maintainer of the website paybyphoneapis.com doesn't provide any documentation for his API, do you have some recommendation if I would like extends some functionnality of paybybot3?

A second question, If I understand correctly, paybybot3 base on a API from a reverse engineering process, the API website is maintained by a unknown people. The maintainer of API doesn't decide to release a open source version of paybyphone API that people can run in their local machine, but he release a free website API.
When the user use paybybot3, he will send his account and password to `paybyphoneapis.com` maintained by a unknown people. So users can't guarante security of their PayByPhone account.

**Comment by rklf** [comment]
?

`paybyphoneapis.com` is owned and maintained by PayByPhone company, not by unknown people. Users credentials goes to official PayByPhone API as it would do if user would use the official app.
