### ISSUE TITLE
Integrate directly a PayByPhone API directly into paybybot3

### ISSUE THREAD

**Issue by dev590t** [rklf/paybybot3#11]
Hello,

I have contacted PayByPhone customer support to verify if paybyphoneapis.com is owned and maintained by PayByPhone company. That is his answer:
```
I confirm that this site is not recognized as belonging to our company's domain.

Unfortunately, we do not provide APIs for developers.
```
paybyphoneapis.com is managed by a third party.
I think pass account and password to a third party could has some security issue. We don't know if this third party website is reliable. If a malicious people get user account and password from paybyphoneapis.com, he can use CB of the account to buy parking tickets for other cars.
And if one day, the website is down, paybybot3 will don't work. All software system build on is less robust than if paybybot3 communicate directly with PayByPhone official website.

I think that could be interesting to integrate directly a PayByPhone API from reverse engineering directly into paybybot3, instead using a  third party website API. What do you think?

**Comment by rklf** [comment]
Hello,

Please refrain from opening issues on the repo for non-issues. To clear up the confusion, if you try reverse engineering, you'll see that the official PayByPhone website uses this domain to communicate with its backend.

Customer support might not always have full technical details, so their response could be misleading.

Your concerns about security are generally valid, but in this case, this domain is part of the PayByPhone infrastructure, not a third-party site.

Feel free to verify this yourself through the reverse engineering process to confirm that domain is legitimate.

Thanks.

**Comment by dev590t** [comment]
Thank you for clarifying my concern. 

> Please refrain from opening issues on the repo for non-issues.

Maybe the repo can activate the discussion feature of Github, so developer can discuss about the project. Currently, we can only communicate through issues.
