### ISSUE TITLE
How can I use?

### ISSUE THREAD

**Issue by Sacha338** [rklf/paybybot3#3]
Hello, I'm trying to use this module, but I don't understand it. Would it be possible to explain it to me?
Thank you

---
_Original content: Bonjour, j'essaie d'utiliser ce module, sauf que je ne comprend pas, est ce que ce serait possible de m'expliquer.
Merci_

**Comment by rklf** [comment]
Can you first read [this](https://github.com/rklf/paybybot3#installation) and then elaborate if needed?

**Comment by Sacha338** [comment]
Je l'ai lu sauf que je n'arrive pas à comprendre comment accéder au répertoire ~/.config/

**Comment by Sacha338** [comment]
Je suis sous WINDOWS

**Comment by rklf** [comment]
Should be the same on Windows too (in `C:\Users\<username>/.config/paybybot3.yml`) but you can still use `--config` followed by your `paybybot3.yml` config file path (which will be used in prior of default config from `~/.config/`) as mentioned in [README.md](https://github.com/rklf/paybybot3/#usage)

**Comment by Sacha338** [comment]
Ok thanks.
